apiVersion: v1
kind: Service
metadata:
  name: openplc-runtime
  namespace: openplc
  labels:
    app: openplc-runtime
spec:
  type: ClusterIP
  ports:
    - name: web
      port: YOUR_API_PORT
      targetPort: YOUR_API_PORT
    - name: modbus
      port: 502
      targetPort: 502
  selector:
    app: openplc-runtime
