apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: data-publisher-health
  namespace: data-sources
  labels:
    app: manufacturing-data-publisher
    component: data-publisher
spec:
  entryPoints:
    - datasources
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: manufacturing-data-publisher
      port: YOUR_API_PORT_2
