apiVersion: v1
kind: Service
metadata:
  name: manufacturing-data-publisher
  namespace: data-sources
  labels:
    app: manufacturing-data-publisher
    component: data-publisher
spec:
  type: ClusterIP
  ports:
  - name: health
    port: YOUR_API_PORT_2
    targetPort: YOUR_API_PORT_2
    protocol: TCP
  selector:
    app: manufacturing-data-publisher
    component: data-publisher
