apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: opc-ua-simulator
  namespace: data-sources
  labels:
    app: opc-ua-simulator
    component: data-source
spec:
  entryPoints:
    - opcua
  routes:
  - match: HostSNI(`*`)
    services:
    - name: opc-ua-simulator
      port: YOUR_OPCUA_PORT
