apiVersion: v1
kind: Service
metadata:
  name: opc-ua-simulator
  namespace: data-sources
  labels:
    app: opc-ua-simulator
    component: data-source
spec:
  type: ClusterIP
  ports:
  - name: opcua
    port: YOUR_OPCUA_PORT
    targetPort: YOUR_OPCUA_PORT
    protocol: TCP
  selector:
    app: opc-ua-simulator
    component: data-source
