apiVersion: v1
kind: Service
metadata:
  name: mqtt-middleware
  namespace: backend-apis
  labels:
    app: mqtt-middleware
    component: middleware
spec:
  type: ClusterIP
  ports:
  - name: http
    port: YOUR_API_PORT
    targetPort: YOUR_API_PORT
    protocol: TCP
  selector:
    app: mqtt-middleware
    component: middleware
