apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: neo4j
  labels:
    app: neo4j
    component: graph-database
data:
  NEO4J_PLUGINS: '["apoc"]'
  NEO4J_dbms_memory_heap_initial__size: "1G"
  NEO4J_dbms_memory_heap_max__size: "2G"
  NEO4J_dbms_memory_pagecache_size: "1G"
  NEO4J_dbms_memory_transaction_total_max: "3G"
  NEO4J_dbms_memory_transaction_max: "1G"
  NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
  NEO4J_dbms_security_procedures_allowlist: "apoc.*"
  NEO4J_server_config_strict__validation_enabled: "false"
