apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mssql-tcp
  namespace: mssql
  labels:
    app: mssql
    component: database
spec:
  entryPoints:
    - mssql
  routes:
  - match: HostSNI(`*`)
    services:
    - name: mssql
      port: YOUR_MSSQL_PORT
