apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: mssql
  labels:
    app: mssql
    component: database
spec:
  type: ClusterIP
  selector:
    app: mssql
    component: database
  ports:
  - name: mssql
    port: YOUR_MSSQL_PORT
    targetPort: YOUR_MSSQL_PORT
    protocol: TCP
