apiVersion: v1
kind: Service
metadata:
  name: ml-predictor
  namespace: backend-apis
  labels:
    app: ml-predictor
spec:
  type: ClusterIP
  ports:
    - port: YOUR_API_PORT_3
      targetPort: YOUR_API_PORT_3
      protocol: TCP
      name: http
  selector:
    app: ml-predictor
